//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PanelBridge.Panels.Econ.Generated
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SessionStartArgsBase", Namespace="http://example.com/Econ/Core/V1/Security")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(PanelBridge.Panels.Econ.Generated.SessionStartArgs))]
    internal partial class SessionStartArgsBase : object
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SessionStartArgs", Namespace="http://example.com/Econ/V1/Security")]
    internal partial class SessionStartArgs : PanelBridge.Panels.Econ.Generated.SessionStartArgsBase
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SessionStartResultBase", Namespace="http://example.com/Econ/Core/V1/Security")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(PanelBridge.Panels.Econ.Generated.SessionStartResult))]
    internal partial class SessionStartResultBase : object
    {
        
        private int ResultField;
        
        private string SessionPasswordField;
        
        private string SessionUserNameField;
        
        private int DaysBeforePasswordExpiryField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal int Result
        {
            get
            {
                return this.ResultField;
            }
            set
            {
                this.ResultField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string SessionPassword
        {
            get
            {
                return this.SessionPasswordField;
            }
            set
            {
                this.SessionPasswordField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string SessionUserName
        {
            get
            {
                return this.SessionUserNameField;
            }
            set
            {
                this.SessionUserNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        internal int DaysBeforePasswordExpiry
        {
            get
            {
                return this.DaysBeforePasswordExpiryField;
            }
            set
            {
                this.DaysBeforePasswordExpiryField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SessionStartResult", Namespace="http://example.com/Econ/V1/Security")]
    internal partial class SessionStartResult : PanelBridge.Panels.Econ.Generated.SessionStartResultBase
    {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://example.com/Econ/V1/Security", ConfigurationName="PanelBridge.Panels.Econ.Generated.IStartSessionService")]
    internal interface IStartSessionService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://example.com/Econ/V1/Security/IStartSessionService/StartSession", ReplyAction="http://example.com/Econ/V1/Security/IStartSessionService/StartSessionR" +
            "esponse")]
        PanelBridge.Panels.Econ.Generated.SessionStartResult StartSession(PanelBridge.Panels.Econ.Generated.SessionStartArgs args);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://example.com/Econ/V1/Security/IStartSessionService/StartSession", ReplyAction="http://example.com/Econ/V1/Security/IStartSessionService/StartSessionR" +
            "esponse")]
        System.Threading.Tasks.Task<PanelBridge.Panels.Econ.Generated.SessionStartResult> StartSessionAsync(PanelBridge.Panels.Econ.Generated.SessionStartArgs args);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    internal interface IStartSessionServiceChannel : PanelBridge.Panels.Econ.Generated.IStartSessionService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    internal partial class StartSessionServiceClient : System.ServiceModel.ClientBase<PanelBridge.Panels.Econ.Generated.IStartSessionService>, PanelBridge.Panels.Econ.Generated.IStartSessionService
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
    public StartSessionServiceClient() : 
                base(StartSessionServiceClient.GetDefaultBinding(), StartSessionServiceClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IStartSessionService.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public StartSessionServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(StartSessionServiceClient.GetBindingForEndpoint(endpointConfiguration), StartSessionServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public StartSessionServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(StartSessionServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public StartSessionServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(StartSessionServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public StartSessionServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public PanelBridge.Panels.Econ.Generated.SessionStartResult StartSession(PanelBridge.Panels.Econ.Generated.SessionStartArgs args)
        {
            return base.Channel.StartSession(args);
        }
        
        public System.Threading.Tasks.Task<PanelBridge.Panels.Econ.Generated.SessionStartResult> StartSessionAsync(PanelBridge.Panels.Econ.Generated.SessionStartArgs args)
        {
            return base.Channel.StartSessionAsync(args);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        #if !NET6_0_OR_GREATER
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        #endif
  
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IStartSessionService))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.TransportWithMessageCredential;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IStartSessionService))
            {
                return new System.ServiceModel.EndpointAddress("https://<panel-host>/v1_00/StartSessionService.svc");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return StartSessionServiceClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IStartSessionService);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return StartSessionServiceClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IStartSessionService);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IStartSessionService,
        }
    }
}
